name: flutter_fundraising_goal_chart
description: "Fundraising Goal Chart Realtime Web App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  get_it: ^8.0.3
  provider: ^6.1.2
  another_flushbar: ^1.12.30
  go_router: ^14.8.0
  uuid: ^4.5.1
  intl: ^0.20.2
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^28.2.6
  gauge_indicator: ^0.4.3
  flutter_screenutil: ^5.9.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  easy_stepper: ^0.8.5+1
  flutter_widget_from_html: ^0.16.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/
